// 定义所有年份的夏季奥运会奖牌数据字典（每届取奖牌总数前32名国家）
const olympicData = {
    // 1896 Athens（共11个国家/地区）
    1896: [
        { name: 'Greece', value: 47 },
        { name: 'United States', value: 20 },
        { name: 'Germany', value: 13 },
        { name: 'France', value: 11 },
        { name: 'United Kingdom', value: 7 },
        { name: 'Denmark', value: 6 },
        { name: 'Hungary', value: 6 },
        { name: 'Austria', value: 5 },
        { name: 'Switzerland', value: 3 },
        { name: 'Australia', value: 2 },
        { name: 'Mixed Team', value: 2 }
    ],

    // 1900 Paris（共21个国家/地区）
    1900: [
        { name: 'France', value: 110 },
        { name: 'United States', value: 48 },
        { name: 'United Kingdom', value: 35 },
        { name: 'Belgium', value: 18 },
        { name: 'Germany', value: 9 },
        { name: 'Switzerland', value: 9 },
        { name: 'Austria', value: 6 },
        { name: 'Denmark', value: 6 },
        { name: 'Mixed Team', value: 6 },
        { name: 'Netherlands', value: 6 },
        { name: 'Australia', value: 5 },
        { name: 'Hungary', value: 5 },
        { name: 'Italy', value: 5 },
        { name: 'Norway', value: 5 },
        { name: 'Bohemia', value: 2 },
        { name: 'Canada', value: 2 },
        { name: 'Cuba', value: 2 },
        { name: 'India', value: 2 },
        { name: 'Luxembourg', value: 1 },
        { name: 'Spain', value: 1 },
        { name: 'Sweden', value: 1 }
    ],

    // 1904 St Louis（共13个国家/地区）
    1904: [
        { name: 'United States', value: 234 },
        { name: 'Germany', value: 15 },
        { name: 'Canada', value: 6 },
        { name: 'Australia', value: 4 },
        { name: 'Hungary', value: 4 },
        { name: 'Austria', value: 3 },
        { name: 'Cuba', value: 3 },
        { name: 'Switzerland', value: 3 },
        { name: 'Greece', value: 2 },
        { name: 'Norway', value: 2 },
        { name: 'United Kingdom', value: 2 },
        { name: 'France', value: 1 },
        { name: 'Mixed Team', value: 1 }
    ],

    // 1908 London（共19个国家/地区）
    1908: [
        { name: 'United Kingdom', value: 146 },
        { name: 'United States', value: 47 },
        { name: 'Sweden', value: 25 },
        { name: 'France', value: 19 },
        { name: 'Canada', value: 16 },
        { name: 'Germany', value: 13 },
        { name: 'Hungary', value: 9 },
        { name: 'Belgium', value: 8 },
        { name: 'Norway', value: 8 },
        { name: 'Australasia', value: 5 },
        { name: 'Denmark', value: 5 },
        { name: 'Finland', value: 5 },
        { name: 'Greece', value: 4 },
        { name: 'Italy', value: 4 },
        { name: 'Russian Empire', value: 3 },
        { name: 'Bohemia', value: 2 },
        { name: 'Netherlands', value: 2 },
        { name: 'South Africa', value: 2 },
        { name: 'Austria', value: 1 }
    ],

    // 1912 Stockholm（共18个国家/地区）
    1912: [
        { name: 'Sweden', value: 65 },
        { name: 'United States', value: 63 },
        { name: 'United Kingdom', value: 41 },
        { name: 'Finland', value: 26 },
        { name: 'Germany', value: 25 },
        { name: 'France', value: 14 },
        { name: 'Denmark', value: 12 },
        { name: 'Norway', value: 10 },
        { name: 'Canada', value: 8 },
        { name: 'Hungary', value: 8 },
        { name: 'Australasia', value: 7 },
        { name: 'Belgium', value: 6 },
        { name: 'Italy', value: 6 },
        { name: 'South Africa', value: 6 },
        { name: 'Russian Empire', value: 5 },
        { name: 'Austria', value: 4 },
        { name: 'Netherlands', value: 3 },
        { name: 'Greece', value: 2 }
    ],

    // 1920 Antwerp（共22个国家/地区）
    1920: [
        { name: 'United States', value: 95 },
        { name: 'Sweden', value: 64 },
        { name: 'United Kingdom', value: 42 },
        { name: 'France', value: 41 },
        { name: 'Belgium', value: 36 },
        { name: 'Finland', value: 34 },
        { name: 'Norway', value: 31 },
        { name: 'Italy', value: 23 },
        { name: 'Denmark', value: 13 },
        { name: 'Netherlands', value: 11 },
        { name: 'Switzerland', value: 11 },
        { name: 'South Africa', value: 10 },
        { name: 'Canada', value: 9 },
        { name: 'Australia', value: 3 },
        { name: 'Brazil', value: 3 },
        { name: 'Estonia', value: 3 },
        { name: 'Czechoslovakia', value: 2 },
        { name: 'Japan', value: 2 },
        { name: 'Spain', value: 2 },
        { name: 'Greece', value: 1 },
        { name: 'Luxembourg', value: 1 },
        { name: 'New Zealand', value: 1 }
    ],

    // 1924 Paris（共27个国家/地区）
    1924: [
        { name: 'United States', value: 99 },
        { name: 'France', value: 38 },
        { name: 'Finland', value: 37 },
        { name: 'United Kingdom', value: 34 },
        { name: 'Sweden', value: 29 },
        { name: 'Switzerland', value: 25 },
        { name: 'Italy', value: 16 },
        { name: 'Belgium', value: 13 },
        { name: 'Czechoslovakia', value: 10 },
        { name: 'Netherlands', value: 10 },
        { name: 'Norway', value: 10 },
        { name: 'Denmark', value: 9 },
        { name: 'Hungary', value: 9 },
        { name: 'Argentina', value: 6 },
        { name: 'Australia', value: 6 },
        { name: 'Estonia', value: 6 },
        { name: 'Austria', value: 4 },
        { name: 'Canada', value: 4 },
        { name: 'South Africa', value: 3 },
        { name: 'Poland', value: 2 },
        { name: 'Yugoslavia', value: 2 },
        { name: 'Haiti', value: 1 },
        { name: 'Japan', value: 1 },
        { name: 'New Zealand', value: 1 },
        { name: 'Portugal', value: 1 },
        { name: 'Romania', value: 1 },
        { name: 'Uruguay', value: 1 }
    ],

    // 1928 Amsterdam（共32个国家/地区）
    1928: [
        { name: 'United States', value: 56 },
        { name: 'Germany', value: 31 },
        { name: 'Finland', value: 25 },
        { name: 'Sweden', value: 25 },
        { name: 'France', value: 21 },
        { name: 'United Kingdom', value: 20 },
        { name: 'Italy', value: 19 },
        { name: 'Netherlands', value: 19 },
        { name: 'Canada', value: 15 },
        { name: 'Switzerland', value: 15 },
        { name: 'Czechoslovakia', value: 9 },
        { name: 'Hungary', value: 9 },
        { name: 'Argentina', value: 7 },
        { name: 'Denmark', value: 6 },
        { name: 'Estonia', value: 5 },
        { name: 'Japan', value: 5 },
        { name: 'Poland', value: 5 },
        { name: 'Yugoslavia', value: 5 },
        { name: 'Australia', value: 4 },
        { name: 'Egypt', value: 4 },
        { name: 'Norway', value: 4 },
        { name: 'Austria', value: 3 },
        { name: 'Belgium', value: 3 },
        { name: 'South Africa', value: 3 },
        { name: 'Chile', value: 1 },
        { name: 'Haiti', value: 1 },
        { name: 'India', value: 1 },
        { name: 'Ireland', value: 1 },
        { name: 'New Zealand', value: 1 },
        { name: 'Philippines', value: 1 },
        { name: 'Portugal', value: 1 },
        { name: 'Spain', value: 1 }
    ],

    // 1932 Los Angeles（共27个国家/地区）
    1932: [
        { name: 'United States', value: 103 },
        { name: 'Italy', value: 36 },
        { name: 'Finland', value: 25 },
        { name: 'Sweden', value: 23 },
        { name: 'Germany', value: 20 },
        { name: 'France', value: 19 },
        { name: 'Japan', value: 18 },
        { name: 'United Kingdom', value: 16 },
        { name: 'Canada', value: 15 },
        { name: 'Hungary', value: 15 },
        { name: 'Netherlands', value: 7 },
        { name: 'Poland', value: 7 },
        { name: 'Denmark', value: 6 },
        { name: 'Australia', value: 5 },
        { name: 'Austria', value: 5 },
        { name: 'South Africa', value: 5 },
        { name: 'Argentina', value: 4 },
        { name: 'Czechoslovakia', value: 4 },
        { name: 'Philippines', value: 3 },
        { name: 'Ireland', value: 2 },
        { name: 'Mexico', value: 2 },
        { name: 'India', value: 1 },
        { name: 'Latvia', value: 1 },
        { name: 'New Zealand', value: 1 },
        { name: 'Spain', value: 1 },
        { name: 'Switzerland', value: 1 },
        { name: 'Uruguay', value: 1 }
    ],

    // 1936 Berlin（共32个国家/地区）
    1936: [
        { name: 'Germany', value: 89 },
        { name: 'United States', value: 56 },
        { name: 'Italy', value: 22 },
        { name: 'Sweden', value: 20 },
        { name: 'Finland', value: 19 },
        { name: 'France', value: 19 },
        { name: 'Japan', value: 18 },
        { name: 'Netherlands', value: 17 },
        { name: 'Hungary', value: 16 },
        { name: 'Switzerland', value: 15 },
        { name: 'United Kingdom', value: 14 },
        { name: 'Austria', value: 13 },
        { name: 'Canada', value: 9 },
        { name: 'Czechoslovakia', value: 8 },
        { name: 'Argentina', value: 7 },
        { name: 'Estonia', value: 7 },
        { name: 'Norway', value: 6 },
        { name: 'Poland', value: 6 },
        { name: 'Denmark', value: 5 },
        { name: 'Egypt', value: 5 },
        { name: 'Mexico', value: 3 },
        { name: 'Belgium', value: 2 },
        { name: 'Latvia', value: 2 },
        { name: 'Turkey', value: 2 },
        { name: 'Australia', value: 1 },
        { name: 'India', value: 1 },
        { name: 'New Zealand', value: 1 },
        { name: 'Philippines', value: 1 },
        { name: 'Portugal', value: 1 },
        { name: 'Romania', value: 1 },
        { name: 'South Africa', value: 1 },
        { name: 'Yugoslavia', value: 1 }
    ],

    // 1948 London（共32个国家/地区）
    1948: [
        { name: 'United States', value: 84 },
        { name: 'Sweden', value: 44 },
        { name: 'France', value: 29 },
        { name: 'Hungary', value: 27 },
        { name: 'Italy', value: 27 },
        { name: 'United Kingdom', value: 23 },
        { name: 'Denmark', value: 20 },
        { name: 'Finland', value: 20 },
        { name: 'Switzerland', value: 20 },
        { name: 'Netherlands', value: 16 },
        { name: 'Australia', value: 13 },
        { name: 'Turkey', value: 12 },
        { name: 'Czechoslovakia', value: 11 },
        { name: 'Argentina', value: 7 },
        { name: 'Belgium', value: 7 },
        { name: 'Norway', value: 7 },
        { name: 'Egypt', value: 5 },
        { name: 'Mexico', value: 5 },
        { name: 'Austria', value: 4 },
        { name: 'South Africa', value: 4 },
        { name: 'Canada', value: 3 },
        { name: 'Jamaica, British', value: 3 },
        { name: 'Korea', value: 2 },
        { name: 'Panama', value: 2 },
        { name: 'Portugal', value: 2 },
        { name: 'Uruguay', value: 2 },
        { name: 'Yugoslavia', value: 2 },
        { name: 'Brazil', value: 1 },
        { name: 'Ceylon', value: 1 },
        { name: 'Cuba', value: 1 },
        { name: 'India', value: 1 },
        { name: 'Iran', value: 1 }
    ],

    // 1952 Helsinki（共32个国家/地区）
    1952: [
        { name: 'United States', value: 76 },
        { name: 'Russia', value: 71 },
        { name: 'Hungary', value: 42 },
        { name: 'Sweden', value: 35 },
        { name: 'Germany', value: 24 },
        { name: 'Finland', value: 22 },
        { name: 'Italy', value: 21 },
        { name: 'France', value: 18 },
        { name: 'Switzerland', value: 14 },
        { name: 'Czechoslovakia', value: 13 },
        { name: 'Australia', value: 11 },
        { name: 'United Kingdom', value: 11 },
        { name: 'South Africa', value: 10 },
        { name: 'Japan', value: 9 },
        { name: 'Iran', value: 7 },
        { name: 'Denmark', value: 6 },
        { name: 'Argentina', value: 5 },
        { name: 'Jamaica, British', value: 5 },
        { name: 'Netherlands', value: 5 },
        { name: 'Norway', value: 5 },
        { name: 'Belgium', value: 4 },
        { name: 'Poland', value: 4 },
        { name: 'Romania', value: 4 },
        { name: 'Brazil', value: 3 },
        { name: 'Canada', value: 3 },
        { name: 'New Zealand', value: 3 },
        { name: 'Turkey', value: 3 },
        { name: 'Yugoslavia', value: 3 },
        { name: 'Austria', value: 2 },
        { name: 'Chile', value: 2 },
        { name: 'India', value: 2 },
        { name: 'Korea', value: 2 }
    ],

    // 1956 Melbourne / Stockholm（共32个国家/地区）
    1956: [
        { name: 'Russia', value: 98 },
        { name: 'United States', value: 74 },
        { name: 'Australia', value: 35 },
        { name: 'Hungary', value: 26 },
        { name: 'Unified Team of Germany', value: 26 },
        { name: 'Italy', value: 25 },
        { name: 'United Kingdom', value: 24 },
        { name: 'Japan', value: 19 },
        { name: 'Sweden', value: 19 },
        { name: 'Finland', value: 15 },
        { name: 'France', value: 14 },
        { name: 'Romania', value: 13 },
        { name: 'Poland', value: 9 },
        { name: 'Turkey', value: 7 },
        { name: 'Canada', value: 6 },
        { name: 'Czechoslovakia', value: 6 },
        { name: 'Bulgaria', value: 5 },
        { name: 'Iran', value: 5 },
        { name: 'Ireland', value: 5 },
        { name: 'Chile', value: 4 },
        { name: 'Denmark', value: 4 },
        { name: 'South Africa', value: 4 },
        { name: 'Norway', value: 3 },
        { name: 'Yugoslavia', value: 3 },
        { name: 'Argentina', value: 2 },
        { name: 'Austria', value: 2 },
        { name: 'Belgium', value: 2 },
        { name: 'Korea', value: 2 },
        { name: 'Mexico', value: 2 },
        { name: 'New Zealand', value: 2 },
        { name: 'Bahamas', value: 1 },
        { name: 'Brazil', value: 1 }
    ],

    // 1960 Rome（共32个国家/地区）
    1960: [
        { name: 'Russia', value: 103 },
        { name: 'United States', value: 71 },
        { name: 'Unified Team of Germany', value: 42 },
        { name: 'Italy', value: 36 },
        { name: 'Australia', value: 22 },
        { name: 'Hungary', value: 21 },
        { name: 'Poland', value: 21 },
        { name: 'United Kingdom', value: 20 },
        { name: 'Japan', value: 18 },
        { name: 'Romania', value: 10 },
        { name: 'Turkey', value: 9 },
        { name: 'Czechoslovakia', value: 8 },
        { name: 'Bulgaria', value: 7 },
        { name: 'Denmark', value: 6 },
        { name: 'Sweden', value: 6 },
        { name: 'Switzerland', value: 6 },
        { name: 'Finland', value: 5 },
        { name: 'France', value: 5 },
        { name: 'Belgium', value: 4 },
        { name: 'Iran', value: 4 },
        { name: 'Netherlands', value: 3 },
        { name: 'New Zealand', value: 3 },
        { name: 'South Africa', value: 3 },
        { name: 'Argentina', value: 2 },
        { name: 'Austria', value: 2 },
        { name: 'Brazil', value: 2 },
        { name: 'British West Indies', value: 2 },
        { name: 'Pakistan', value: 2 },
        { name: 'United Arab Republic (Egypt, Syria)', value: 2 },
        { name: 'Yugoslavia', value: 2 },
        { name: 'Canada', value: 1 },
        { name: 'Ethiopia', value: 1 }
    ],

    // 1964 Tokyo（共32个国家/地区）
    1964: [
        { name: 'Russia', value: 96 },
        { name: 'United States', value: 90 },
        { name: 'Unified Team of Germany', value: 50 },
        { name: 'Japan', value: 29 },
        { name: 'Italy', value: 27 },
        { name: 'Poland', value: 23 },
        { name: 'Hungary', value: 22 },
        { name: 'Australia', value: 18 },
        { name: 'United Kingdom', value: 18 },
        { name: 'France', value: 15 },
        { name: 'Czechoslovakia', value: 14 },
        { name: 'Romania', value: 12 },
        { name: 'Bulgaria', value: 10 },
        { name: 'Netherlands', value: 10 },
        { name: 'Sweden', value: 8 },
        { name: 'Denmark', value: 6 },
        { name: 'Turkey', value: 6 },
        { name: 'Finland', value: 5 },
        { name: 'New Zealand', value: 5 },
        { name: 'Yugoslavia', value: 5 },
        { name: 'Canada', value: 4 },
        { name: 'Switzerland', value: 4 },
        { name: 'Belgium', value: 3 },
        { name: 'Korea', value: 3 },
        { name: 'Trinidad and Tobago', value: 3 },
        { name: 'Iran', value: 2 },
        { name: 'Tunisia', value: 2 },
        { name: 'Argentina', value: 1 },
        { name: 'Bahamas', value: 1 },
        { name: 'Brazil', value: 1 },
        { name: 'Cuba', value: 1 },
        { name: 'Ethiopia', value: 1 }
    ],

    // 1968 Mexico（共32个国家/地区）
    1968: [
        { name: 'United States', value: 107 },
        { name: 'Russia', value: 91 },
        { name: 'Hungary', value: 32 },
        { name: 'Federal Republic of Germany', value: 26 },
        { name: 'East Germany', value: 25 },
        { name: 'Japan', value: 25 },
        { name: 'Poland', value: 18 },
        { name: 'Australia', value: 17 },
        { name: 'Italy', value: 16 },
        { name: 'France', value: 15 },
        { name: 'Romania', value: 15 },
        { name: 'Czechoslovakia', value: 13 },
        { name: 'United Kingdom', value: 13 },
        { name: 'Bulgaria', value: 9 },
        { name: 'Kenya', value: 9 },
        { name: 'Mexico', value: 9 },
        { name: 'Denmark', value: 8 },
        { name: 'Yugoslavia', value: 8 },
        { name: 'Netherlands', value: 7 },
        { name: 'Canada', value: 5 },
        { name: 'Iran', value: 5 },
        { name: 'Switzerland', value: 5 },
        { name: 'Austria', value: 4 },
        { name: 'Cuba', value: 4 },
        { name: 'Finland', value: 4 },
        { name: 'Mongolia', value: 4 },
        { name: 'Sweden', value: 4 },
        { name: 'Brazil', value: 3 },
        { name: 'New Zealand', value: 3 },
        { name: 'Argentina', value: 2 },
        { name: 'Belgium', value: 2 },
        { name: 'Ethiopia', value: 2 }
    ],

    // 1972 Munich（共32个国家/地区）
    1972: [
        { name: 'Russia', value: 99 },
        { name: 'United States', value: 94 },
        { name: 'East Germany', value: 66 },
        { name: 'Federal Republic of Germany', value: 40 },
        { name: 'Hungary', value: 35 },
        { name: 'Japan', value: 29 },
        { name: 'Bulgaria', value: 21 },
        { name: 'Poland', value: 21 },
        { name: 'Italy', value: 18 },
        { name: 'United Kingdom', value: 18 },
        { name: 'Australia', value: 17 },
        { name: 'Romania', value: 16 },
        { name: 'Sweden', value: 16 },
        { name: 'France', value: 13 },
        { name: 'Kenya', value: 9 },
        { name: 'Cuba', value: 8 },
        { name: 'Czechoslovakia', value: 8 },
        { name: 'Finland', value: 8 },
        { name: 'Canada', value: 5 },
        { name: 'Korea DPR', value: 5 },
        { name: 'Netherlands', value: 5 },
        { name: 'Yugoslavia', value: 5 },
        { name: 'Norway', value: 4 },
        { name: 'Austria', value: 3 },
        { name: 'Colombia', value: 3 },
        { name: 'Iran', value: 3 },
        { name: 'New Zealand', value: 3 },
        { name: 'Switzerland', value: 3 },
        { name: 'Belgium', value: 2 },
        { name: 'Brazil', value: 2 },
        { name: 'Ethiopia', value: 2 },
        { name: 'Greece', value: 2 }
    ],

    // 1976 Montreal（共32个国家/地区）
    1976: [
        { name: 'Russia', value: 125 },
        { name: 'United States', value: 94 },
        { name: 'East Germany', value: 90 },
        { name: 'Federal Republic of Germany', value: 39 },
        { name: 'Romania', value: 27 },
        { name: 'Poland', value: 26 },
        { name: 'Japan', value: 25 },
        { name: 'Bulgaria', value: 22 },
        { name: 'Hungary', value: 22 },
        { name: 'Cuba', value: 13 },
        { name: 'Italy', value: 13 },
        { name: 'United Kingdom', value: 13 },
        { name: 'Canada', value: 11 },
        { name: 'France', value: 9 },
        { name: 'Czechoslovakia', value: 8 },
        { name: 'Yugoslavia', value: 8 },
        { name: 'Belgium', value: 6 },
        { name: 'Finland', value: 6 },
        { name: 'Korea', value: 6 },
        { name: 'Australia', value: 5 },
        { name: 'Netherlands', value: 5 },
        { name: 'Sweden', value: 5 },
        { name: 'New Zealand', value: 4 },
        { name: 'Switzerland', value: 4 },
        { name: 'Denmark', value: 3 },
        { name: 'Brazil', value: 2 },
        { name: 'Iran', value: 2 },
        { name: 'Jamaica', value: 2 },
        { name: 'Korea DPR', value: 2 },
        { name: 'Mexico', value: 2 },
        { name: 'Norway', value: 2 },
        { name: 'Portugal', value: 2 }
    ],

    // 1980 Moscow（共32个国家/地区）
    1980: [
        { name: 'Russia', value: 195 },
        { name: 'East Germany', value: 126 },
        { name: 'Bulgaria', value: 41 },
        { name: 'Hungary', value: 32 },
        { name: 'Poland', value: 32 },
        { name: 'Romania', value: 25 },
        { name: 'United Kingdom', value: 21 },
        { name: 'Cuba', value: 20 },
        { name: 'Italy', value: 15 },
        { name: 'Czechoslovakia', value: 14 },
        { name: 'France', value: 14 },
        { name: 'Sweden', value: 12 },
        { name: 'Australia', value: 9 },
        { name: 'Yugoslavia', value: 9 },
        { name: 'Finland', value: 8 },
        { name: 'Spain', value: 6 },
        { name: 'Denmark', value: 5 },
        { name: 'Korea DPR', value: 5 },
        { name: 'Austria', value: 4 },
        { name: 'Brazil', value: 4 },
        { name: 'Ethiopia', value: 4 },
        { name: 'Mexico', value: 4 },
        { name: 'Mongolia', value: 4 },
        { name: 'Greece', value: 3 },
        { name: 'Jamaica', value: 3 },
        { name: 'Netherlands', value: 3 },
        { name: 'Ireland', value: 2 },
        { name: 'Switzerland', value: 2 },
        { name: 'Tanzania', value: 2 },
        { name: 'Belgium', value: 1 },
        { name: 'Guyana', value: 1 },
        { name: 'India', value: 1 }
    ],

    // 1984 Los Angeles（共32个国家/地区）
    1984: [
        { name: 'United States', value: 174 },
        { name: 'Federal Republic of Germany', value: 59 },
        { name: 'Romania', value: 53 },
        { name: 'Canada', value: 44 },
        { name: 'United Kingdom', value: 37 },
        { name: 'China', value: 32 },
        { name: 'Italy', value: 32 },
        { name: 'Japan', value: 32 },
        { name: 'France', value: 28 },
        { name: 'Australia', value: 24 },
        { name: 'Korea', value: 19 },
        { name: 'Sweden', value: 19 },
        { name: 'Yugoslavia', value: 18 },
        { name: 'Netherlands', value: 13 },
        { name: 'Finland', value: 12 },
        { name: 'New Zealand', value: 11 },
        { name: 'Brazil', value: 8 },
        { name: 'Switzerland', value: 8 },
        { name: 'Denmark', value: 6 },
        { name: 'Mexico', value: 6 },
        { name: 'Spain', value: 5 },
        { name: 'Belgium', value: 4 },
        { name: 'Austria', value: 3 },
        { name: 'Jamaica', value: 3 },
        { name: 'Kenya', value: 3 },
        { name: 'Norway', value: 3 },
        { name: 'Portugal', value: 3 },
        { name: 'Turkey', value: 3 },
        { name: 'Venezuela', value: 3 },
        { name: 'Algeria', value: 2 },
        { name: 'Greece', value: 2 },
        { name: 'Morocco', value: 2 }
    ],

    // 1988 Seoul（共32个国家/地区）
    1988: [
        { name: 'Russia', value: 132 },
        { name: 'East Germany', value: 102 },
        { name: 'United States', value: 94 },
        { name: 'Federal Republic of Germany', value: 40 },
        { name: 'Bulgaria', value: 35 },
        { name: 'Korea', value: 33 },
        { name: 'China', value: 28 },
        { name: 'Romania', value: 24 },
        { name: 'United Kingdom', value: 24 },
        { name: 'Hungary', value: 23 },
        { name: 'France', value: 16 },
        { name: 'Poland', value: 16 },
        { name: 'Australia', value: 14 },
        { name: 'Italy', value: 14 },
        { name: 'Japan', value: 14 },
        { name: 'New Zealand', value: 13 },
        { name: 'Yugoslavia', value: 12 },
        { name: 'Sweden', value: 11 },
        { name: 'Canada', value: 10 },
        { name: 'Kenya', value: 9 },
        { name: 'Netherlands', value: 9 },
        { name: 'Czechoslovakia', value: 8 },
        { name: 'Brazil', value: 6 },
        { name: 'Norway', value: 5 },
        { name: 'Denmark', value: 4 },
        { name: 'Finland', value: 4 },
        { name: 'Spain', value: 4 },
        { name: 'Switzerland', value: 4 },
        { name: 'Morocco', value: 3 },
        { name: 'Argentina', value: 2 },
        { name: 'Belgium', value: 2 },
        { name: 'Jamaica', value: 2 }
    ],

    // 1992 Barcelona（共32个国家/地区）
    1992: [
        { name: 'Unified Team (ex USSR)', value: 112 },
        { name: 'United States', value: 108 },
        { name: 'Germany', value: 82 },
        { name: 'China', value: 54 },
        { name: 'Cuba', value: 31 },
        { name: 'Hungary', value: 30 },
        { name: 'France', value: 29 },
        { name: 'Korea', value: 29 },
        { name: 'Australia', value: 27 },
        { name: 'Japan', value: 22 },
        { name: 'Spain', value: 22 },
        { name: 'United Kingdom', value: 20 },
        { name: 'Italy', value: 19 },
        { name: 'Poland', value: 19 },
        { name: 'Canada', value: 18 },
        { name: 'Romania', value: 18 },
        { name: 'Bulgaria', value: 16 },
        { name: 'Netherlands', value: 15 },
        { name: 'Sweden', value: 12 },
        { name: 'New Zealand', value: 10 },
        { name: 'Korea DPR', value: 9 },
        { name: 'Kenya', value: 8 },
        { name: 'Czechoslovakia', value: 7 },
        { name: 'Norway', value: 7 },
        { name: 'Denmark', value: 6 },
        { name: 'Turkey', value: 6 },
        { name: 'Finland', value: 5 },
        { name: 'Indonesia', value: 5 },
        { name: 'Jamaica', value: 4 },
        { name: 'Nigeria', value: 4 },
        { name: 'Belgium', value: 3 },
        { name: 'Brazil', value: 3 }
    ],

    // 1996 Atlanta（共32个国家/地区）
    1996: [
        { name: 'United States', value: 101 },
        { name: 'Germany', value: 65 },
        { name: 'Russia', value: 63 },
        { name: 'China', value: 50 },
        { name: 'Australia', value: 41 },
        { name: 'France', value: 37 },
        { name: 'Italy', value: 35 },
        { name: 'Korea', value: 27 },
        { name: 'Cuba', value: 25 },
        { name: 'Ukraine', value: 23 },
        { name: 'Canada', value: 22 },
        { name: 'Hungary', value: 21 },
        { name: 'Romania', value: 20 },
        { name: 'Netherlands', value: 19 },
        { name: 'Poland', value: 17 },
        { name: 'Spain', value: 17 },
        { name: 'Belarus', value: 15 },
        { name: 'Brazil', value: 15 },
        { name: 'Bulgaria', value: 15 },
        { name: 'United Kingdom', value: 15 },
        { name: 'Japan', value: 14 },
        { name: 'Czech Republic', value: 11 },
        { name: 'Kazakhstan', value: 11 },
        { name: 'Greece', value: 8 },
        { name: 'Kenya', value: 8 },
        { name: 'Sweden', value: 8 },
        { name: 'Norway', value: 7 },
        { name: 'Switzerland', value: 7 },
        { name: 'Belgium', value: 6 },
        { name: 'Denmark', value: 6 },
        { name: 'Jamaica', value: 6 },
        { name: 'New Zealand', value: 6 }
    ],

    // 2000 Sydney（共32个国家/地区）
    2000: [
        { name: 'United States', value: 93 },
        { name: 'Russia', value: 89 },
        { name: 'Australia', value: 58 },
        { name: 'China', value: 58 },
        { name: 'Germany', value: 56 },
        { name: 'France', value: 38 },
        { name: 'Italy', value: 34 },
        { name: 'Cuba', value: 29 },
        { name: 'Korea', value: 28 },
        { name: 'United Kingdom', value: 28 },
        { name: 'Romania', value: 26 },
        { name: 'Netherlands', value: 25 },
        { name: 'Ukraine', value: 23 },
        { name: 'Japan', value: 18 },
        { name: 'Belarus', value: 17 },
        { name: 'Hungary', value: 17 },
        { name: 'Canada', value: 14 },
        { name: 'Poland', value: 14 },
        { name: 'Bulgaria', value: 13 },
        { name: 'Greece', value: 13 },
        { name: 'Brazil', value: 12 },
        { name: 'Sweden', value: 12 },
        { name: 'Spain', value: 11 },
        { name: 'Norway', value: 10 },
        { name: 'Jamaica', value: 9 },
        { name: 'Switzerland', value: 9 },
        { name: 'Czech Republic', value: 8 },
        { name: 'Ethiopia', value: 8 },
        { name: 'Kazakhstan', value: 7 },
        { name: 'Kenya', value: 7 },
        { name: 'Denmark', value: 6 },
        { name: 'Georgia', value: 6 }
    ],

    // 2004 Athens（共32个国家/地区）
    2004: [
        { name: 'United States', value: 101 },
        { name: 'Russia', value: 90 },
        { name: 'China', value: 63 },
        { name: 'Australia', value: 50 },
        { name: 'Germany', value: 49 },
        { name: 'Japan', value: 37 },
        { name: 'France', value: 33 },
        { name: 'Italy', value: 32 },
        { name: 'Korea', value: 30 },
        { name: 'United Kingdom', value: 30 },
        { name: 'Cuba', value: 27 },
        { name: 'Netherlands', value: 22 },
        { name: 'Ukraine', value: 22 },
        { name: 'Spain', value: 20 },
        { name: 'Romania', value: 19 },
        { name: 'Hungary', value: 17 },
        { name: 'Greece', value: 16 },
        { name: 'Belarus', value: 13 },
        { name: 'Bulgaria', value: 12 },
        { name: 'Canada', value: 12 },
        { name: 'Brazil', value: 10 },
        { name: 'Poland', value: 10 },
        { name: 'Turkey', value: 10 },
        { name: 'Czech Republic', value: 9 },
        { name: 'Denmark', value: 8 },
        { name: 'Kazakhstan', value: 8 },
        { name: 'Thailand', value: 8 },
        { name: 'Austria', value: 7 },
        { name: 'Ethiopia', value: 7 },
        { name: 'Kenya', value: 7 },
        { name: 'Sweden', value: 7 },
        { name: 'Argentina', value: 6 }
    ],

    // 2008 Beijing（共32个国家/地区）
    2008: [
        { name: 'United States', value: 112 },
        { name: 'China', value: 100 },
        { name: 'Russia', value: 60 },
        { name: 'United Kingdom', value: 51 },
        { name: 'Australia', value: 46 },
        { name: 'France', value: 43 },
        { name: 'Germany', value: 41 },
        { name: 'Korea', value: 32 },
        { name: 'Cuba', value: 30 },
        { name: 'Italy', value: 27 },
        { name: 'Japan', value: 25 },
        { name: 'Ukraine', value: 22 },
        { name: 'Canada', value: 20 },
        { name: 'Spain', value: 19 },
        { name: 'Brazil', value: 17 },
        { name: 'Kenya', value: 16 },
        { name: 'Netherlands', value: 16 },
        { name: 'Belarus', value: 14 },
        { name: 'Jamaica', value: 11 },
        { name: 'Poland', value: 11 },
        { name: 'Hungary', value: 10 },
        { name: 'Kazakhstan', value: 9 },
        { name: 'New Zealand', value: 9 },
        { name: 'Norway', value: 9 },
        { name: 'Romania', value: 9 },
        { name: 'Czech Republic', value: 7 },
        { name: 'Denmark', value: 7 },
        { name: 'Ethiopia', value: 7 },
        { name: 'Georgia', value: 7 },
        { name: 'Switzerland', value: 7 },
        { name: 'Argentina', value: 6 },
        { name: 'Azerbaijan', value: 6 }
    ],

    // 2012 London（共32个国家/地区）
    2012: [
        { name: 'United States', value: 104 },
        { name: 'China', value: 92 },
        { name: 'United Kingdom', value: 65 },
        { name: 'Russia', value: 64 },
        { name: 'Germany', value: 44 },
        { name: 'Japan', value: 38 },
        { name: 'Australia', value: 35 },
        { name: 'France', value: 35 },
        { name: 'Korea', value: 31 },
        { name: 'Italy', value: 28 },
        { name: 'Netherlands', value: 20 },
        { name: 'Spain', value: 20 },
        { name: 'Ukraine', value: 19 },
        { name: 'Canada', value: 18 },
        { name: 'Hungary', value: 18 },
        { name: 'Brazil', value: 17 },
        { name: 'Cuba', value: 15 },
        { name: 'Iran', value: 13 },
        { name: 'Jamaica', value: 13 },
        { name: 'Kenya', value: 13 },
        { name: 'New Zealand', value: 13 },
        { name: 'Czech Republic', value: 11 },
        { name: 'Kazakhstan', value: 11 },
        { name: 'Poland', value: 11 },
        { name: 'Belarus', value: 10 },
        { name: 'Azerbaijan', value: 9 },
        { name: 'Colombia', value: 9 },
        { name: 'Denmark', value: 9 },
        { name: 'Ethiopia', value: 8 },
        { name: 'Mexico', value: 8 },
        { name: 'Sweden', value: 8 },
        { name: 'Korea DPR', value: 7 }
    ],

    // 2016 Rio de Janeiro（共32个国家/地区）
    2016: [
        { name: 'United States', value: 121 },
        { name: 'China', value: 70 },
        { name: 'United Kingdom', value: 67 },
        { name: 'Russia', value: 56 },
        { name: 'France', value: 42 },
        { name: 'Germany', value: 42 },
        { name: 'Japan', value: 41 },
        { name: 'Australia', value: 29 },
        { name: 'Italy', value: 28 },
        { name: 'Canada', value: 22 },
        { name: 'Korea', value: 21 },
        { name: 'Brazil', value: 19 },
        { name: 'Netherlands', value: 19 },
        { name: 'Azerbaijan', value: 18 },
        { name: 'New Zealand', value: 18 },
        { name: 'Kazakhstan', value: 17 },
        { name: 'Spain', value: 17 },
        { name: 'Denmark', value: 15 },
        { name: 'Hungary', value: 15 },
        { name: 'Kenya', value: 13 },
        { name: 'Uzbekistan', value: 13 },
        { name: 'Cuba', value: 11 },
        { name: 'Jamaica', value: 11 },
        { name: 'Poland', value: 11 },
        { name: 'Sweden', value: 11 },
        { name: 'Ukraine', value: 11 },
        { name: 'Croatia', value: 10 },
        { name: 'Czech Republic', value: 10 },
        { name: 'South Africa', value: 10 },
        { name: 'Belarus', value: 9 },
        { name: 'Colombia', value: 8 },
        { name: 'Ethiopia', value: 8 }
    ],

    2020: [
        { name: 'United States', value: 113 },
        { name: 'China', value: 88 },
        { name: 'Russia', value: 71 },
        { name: 'United Kingdom', value: 65 },
        { name: 'Japan', value: 58 },
        { name: 'Australia', value: 46 },
        { name: 'Italy', value: 40 },
        { name: 'Germany', value: 37 },
        { name: 'Netherlands', value: 36 },
        { name: 'France', value: 33 },
        { name: 'Canada', value: 24 },
        { name: 'Brazil', value: 21 },
        { name: 'Korea', value: 20 },
        { name: 'New Zealand', value: 20 },
        { name: 'Hungary', value: 20 },
        { name: 'Ukraine', value: 19 },
        { name: 'Spain', value: 17 },
        { name: 'Cuba', value: 15 },
        { name: 'Poland', value: 14 },
        { name: 'Switzerland', value: 13 },
        { name: 'Turkey', value: 13 },
        { name: 'Denmark', value: 11 },
        { name: 'Czech Republic', value: 11 },
        { name: 'Kenya', value: 10 },
        { name: 'Jamaica', value: 9 },
        { name: 'Serbia', value: 9 },
        { name: 'Sweden', value: 9 },
        { name: 'Croatia', value: 8 },
        { name: 'Georgia', value: 8 },
        { name: 'Kazakhstan', value: 8 },
        { name: 'Norway', value: 8 },
        { name: 'Austria', value: 8 }
    ],

    // 2024 Paris（共32个国家/地区）
    2024: [
        { name: 'United States', value: 126 },
        { name: 'China', value: 91 },
        { name: 'United Kingdom', value: 65 },
        { name: 'France', value: 64 },
        { name: 'Australia', value: 53 },
        { name: 'Japan', value: 45 },
        { name: 'Italy', value: 40 },
        { name: 'Netherlands', value: 34 },
        { name: 'Germany', value: 33 },
        { name: 'Korea', value: 32 },
        { name: 'Canada', value: 27 },
        { name: 'Brazil', value: 20 },
        { name: 'New Zealand', value: 20 },
        { name: 'Hungary', value: 19 },
        { name: 'Spain', value: 18 },
        { name: 'Uzbekistan', value: 13 },
        { name: 'Iran', value: 12 },
        { name: 'Ukraine', value: 12 },
        { name: 'Kenya', value: 11 },
        { name: 'Sweden', value: 11 },
        { name: 'Belgium', value: 10 },
        { name: 'Poland', value: 10 },
        { name: 'Cuba', value: 9 },
        { name: 'Denmark', value: 9 },
        { name: 'Romania', value: 9 },
        { name: 'Greece', value: 8 },
        { name: 'Norway', value: 8 },
        { name: 'Switzerland', value: 8 },
        { name: 'Turkey', value: 8 },
        { name: 'Azerbaijan', value: 7 },
        { name: 'Bulgaria', value: 7 },
        { name: 'Chinese Taipei', value: 7 }
    ]
};